# Simulação de 100 lançamentos de uma moeda
resultado <- sample(              # SAMPLE É ULTILIZADO PARA CRIAR VETORES ALEATÓRIOS
	c("Cara", "Coroa"),           # C É ULTILIZADO PARA CRIAR POSSIBILIDADES, NO CASO, CARA E COROA 
	size = 100,                   # SIZE INDICA A QUANTIDADE DE ELEMENTOS DO VETOR ALEATÓRIO QUE SERÁ CRIADO
	replace = TRUE)               # REPLACE É PARA INDICAR SE O VETOR SERÁ ALEATÓRIO OU NÃO, TRUE INDICA QUE O VETOR SERÁ ALEATÓRIO E NÃO TERÁ REPETIÇÕES, FALSE INDICA QUE O VETOR TERÁ REPETIÇÕES
print(table(resultado))            # PRINT INDICA QUE O RESULTADO SERÁ IMPRESSO NO CONSOLE